# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#make the categories

# category = Category.create([
#   { name: 'Advocacy & Human Rights' },
#   { name: 'Animals' },
#   { name: 'Arts & Culture' },
#   { name: 'Board Development' },
#   { name: 'Children & Youth' },
#   { name: 'Community' },
#   { name: 'Computers & Technology' },
#   { name: 'Crisis Support' },
#   { name: 'Disaster Relief' },
#   { name: 'Education & Literacy' },
#   { name: 'Emergency & Safety' },
#   { name: 'Employment' },
#   { name: 'Environment' },
#   { name: 'Faith-Based' },
#   { name: 'Health & Medicine' },
#   { name: 'Homeless & Housing' },
#   { name: 'Hunger' },
#   { name: 'Migrants & Refugees' },
#   { name: 'International' },
#   { name: 'Justice & Legal' },
#   { name: 'LGBT' },
#   { name: 'Media & Broadcasting' },
#   { name: 'People with Disabilities' },
#   { name: 'Politics' },
#   { name: 'Race & Ethnicity' },
#   { name: 'Seniors' },
#   { name: 'Sports & Recreation' },
#   { name: 'Veterans & Military Families' },
#   { name: 'Women'}
# ])


# city = City.create(name: "New York City", state: "New York", country: "United States", continent: "North America")
# charity = Charity.create(name: "my charity", category_id: 6)
# pairing = CharityCity.create(charity_id: 1, city_id: 1)

City.destroy_all
city = City.create([
{name: 'Los Angeles', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Chicago', state: 'Illinois', continent: 'North America', country: 'United States' },
{name: 'Houston', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Philadelphia', state: 'Pennsylvania', continent: 'North America', country: 'United States' },
{name: 'Phoenix', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'San Antonio', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'San Diego', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Dallas', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'San Jose', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Austin', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Jacksonville', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'San Francisco', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Indianapolis', state: 'Indiana', continent: 'North America', country: 'United States' },
{name: 'Columbus', state: 'Ohio', continent: 'North America', country: 'United States' },
{name: 'Fort Worth', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Charlotte', state: 'North Carolina', continent: 'North America', country: 'United States' },
{name: 'Detroit', state: 'Michigan', continent: 'North America', country: 'United States' },
{name: 'El Paso', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Seattle', state: 'Washington', continent: 'North America', country: 'United States' },
{name: 'Denver', state: 'Colorado', continent: 'North America', country: 'United States' },
{name: 'Washington', state: 'District of Columbia', continent: 'North America', country: 'United States' },
{name: 'Memphis', state: 'Tennessee', continent: 'North America', country: 'United States' },
{name: 'Boston', state: 'Massachusetts', continent: 'North America', country: 'United States' },
{name: 'Nashville', state: 'Tennessee', continent: 'North America', country: 'United States' },
{name: 'Baltimore', state: 'Maryland', continent: 'North America', country: 'United States' },
{name: 'Oklahoma City', state: 'Oklahoma', continent: 'North America', country: 'United States' },
{name: 'Portland', state: 'Oregon', continent: 'North America', country: 'United States' },
{name: 'Las Vegas', state: 'Nevada', continent: 'North America', country: 'United States' },
{name: 'Louisville', state: 'Kentucky', continent: 'North America', country: 'United States' },
{name: 'Milwaukee', state: 'Wisconsin', continent: 'North America', country: 'United States' },
{name: 'Albuquerque', state: 'New Mexico', continent: 'North America', country: 'United States' },
{name: 'Tucson', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'Fresno', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Sacramento', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Long Beach', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Kansas City', state: 'Missouri', continent: 'North America', country: 'United States' },
{name: 'Mesa', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'Atlanta', state: 'Georgia', continent: 'North America', country: 'United States' },
{name: 'Virginia Beach', state: 'Virginia', continent: 'North America', country: 'United States' },
{name: 'Omaha', state: 'Nebraska', continent: 'North America', country: 'United States' },
{name: 'Colorado Springs', state: 'Colorado', continent: 'North America', country: 'United States' },
{name: 'Raleigh', state: 'North Carolina', continent: 'North America', country: 'United States' },
{name: 'Miami', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'Oakland', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Minneapolis', state: 'Minnesota', continent: 'North America', country: 'United States' },
{name: 'Tulsa', state: 'Oklahoma', continent: 'North America', country: 'United States' },
{name: 'Cleveland', state: 'Ohio', continent: 'North America', country: 'United States' },
{name: 'Wichita', state: 'Kansas', continent: 'North America', country: 'United States' },
{name: 'New Orleans', state: 'Louisiana', continent: 'North America', country: 'United States' },
{name: 'Arlington', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Bakersfield', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Tampa', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'Aurora', state: 'Colorado', continent: 'North America', country: 'United States' },
{name: 'Honolulu', state: 'Hawai\'i', continent: 'North America', country: 'United States' },
{name: 'Anaheim', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Santa Ana', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Corpus Christi', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Riverside', state: 'California', continent: 'North America', country: 'United States' },
{name: 'St. Louis', state: 'Missouri', continent: 'North America', country: 'United States' },
{name: 'Lexington', state: 'Kentucky', continent: 'North America', country: 'United States' },
{name: 'Pittsburgh', state: 'Pennsylvania', continent: 'North America', country: 'United States' },
{name: 'Stockton', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Anchorage', state: 'Alaska', continent: 'North America', country: 'United States' },
{name: 'Cincinnati', state: 'Ohio', continent: 'North America', country: 'United States' },
{name: 'Saint Paul', state: 'Minnesota', continent: 'North America', country: 'United States' },
{name: 'Greensboro', state: 'North Carolina', continent: 'North America', country: 'United States' },
{name: 'Toledo', state: 'Ohio', continent: 'North America', country: 'United States' },
{name: 'Newark', state: 'New Jersey', continent: 'North America', country: 'United States' },
{name: 'Plano', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Henderson', state: 'Nevada', continent: 'North America', country: 'United States' },
{name: 'Lincoln', state: 'Nebraska', continent: 'North America', country: 'United States' },
{name: 'Orlando', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'Jersey City', state: 'New Jersey', continent: 'North America', country: 'United States' },
{name: 'Chula Vista', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Buffalo', state: 'New York', continent: 'North America', country: 'United States' },
{name: 'Fort Wayne', state: 'Indiana', continent: 'North America', country: 'United States' },
{name: 'Chandler', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'St. Petersburg', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'Laredo', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Durham', state: 'North Carolina', continent: 'North America', country: 'United States' },
{name: 'Irvine', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Madison', state: 'Wisconsin', continent: 'North America', country: 'United States' },
{name: 'Norfolk', state: 'Virginia', continent: 'North America', country: 'United States' },
{name: 'Lubbock', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Gilbert', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'Winston–Salem', state: 'North Carolina', continent: 'North America', country: 'United States' },
{name: 'Glendale', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'Reno', state: 'Nevada', continent: 'North America', country: 'United States' },
{name: 'Hialeah', state: 'Florida', continent: 'North America', country: 'United States' },
{name: 'Garland', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'Chesapeake', state: 'Virginia', continent: 'North America', country: 'United States' },
{name: 'Irving', state: 'Texas', continent: 'North America', country: 'United States' },
{name: 'North Las Vegas', state: 'Nevada', continent: 'North America', country: 'United States' },
{name: 'Scottsdale', state: 'Arizona', continent: 'North America', country: 'United States' },
{name: 'Baton Rouge', state: 'Louisiana', continent: 'North America', country: 'United States' },
{name: 'Fremont', state: 'California', continent: 'North America', country: 'United States' },
{name: 'Richmond', state: 'Virginia', continent: 'North America', country: 'United States' },
{name: 'Boise', state: 'Idaho', continent: 'North America', country: 'United States' },
{name: 'San Bernardino', state: 'California', continent: 'North America', country: 'United States' }
])

